INSERT INTO PRODUCT (DESCRIPTION, PRICE) VALUES ('iPhone', '100000');
INSERT INTO PRODUCT (DESCRIPTION, PRICE) VALUES ('Kindle Fire', '15000');
INSERT INTO PRODUCT (DESCRIPTION, PRICE) VALUES ('Book', '1500');
INSERT INTO PRODUCT (DESCRIPTION, PRICE) VALUES ('TV', '60000');

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('John', 'Doe', 'john.doe@sample.email.server.com');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Jane', 'Doe', 'jane.doe@sample.email.server.com');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Jack', 'Doe', 'Jack.doe@sample.email.server.com');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Jacky', 'Doe', 'Jacky.doe@sample.email.server.com');

INSERT INTO PURCHASE (PRODUCT_ID, CUSTOMER_ID, PURCHASE_DATE) VALUES ((SELECT ID FROM PRODUCT WHERE DESCRIPTION = 'Book'), (SELECT ID FROM CUSTOMER WHERE FIRST_NAME = 'John' AND LAST_NAME = 'Doe'), '2020-11-23');
INSERT INTO PURCHASE (PRODUCT_ID, CUSTOMER_ID, PURCHASE_DATE) VALUES ((SELECT ID FROM PRODUCT WHERE DESCRIPTION = 'iPhone'), (SELECT ID FROM CUSTOMER WHERE FIRST_NAME = 'Jacky' AND LAST_NAME = 'Doe'), '2019-11-23');

