DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PURCHASE;

CREATE TABLE PRODUCT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(16) NOT NULL,
  PRICE BIGINT NOT NULL
);

CREATE TABLE CUSTOMER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64)
);

CREATE TABLE PURCHASE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT NOT NULL,
  CUSTOMER_ID BIGINT NOT NULL,
  Date DATE
);

ALTER TABLE PURCHASE ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID);
ALTER TABLE PURCHASE ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);
CREATE INDEX IDX_PURCHASE_DATE_ ON PURCHASE(Date);
